#Vagrant File
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.box_version = "20241002.0.0"
  config.vm.network "forwarded_port", guest: 8080, host: 8080

  config.vm.provider "virtualbox" do |vb|
  vb.memory = 6144 # 6 GB of RAM
  vb.cpus = 4      # 4 CPU cores
  end
end
