#Stage 1: Build
FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .
RUN chmod +x docker-entrypoint.sh

# Stage 2: Production
FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci --omit=dev

# Copy built app from builder stage
COPY --from=builder /app ./

EXPOSE 5000

#CMD ["sh", "-c", "npm start", "./docker-entrypoint.sh"]
ENTRYPOINT ["./docker-entrypoint.sh"]
