#Stage 1: Build
FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

# Stage 2: Production
FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci --omit=dev

# Copy built app from builder stage
COPY --from=builder /app ./

# Install postgres client for wait script
#RUN apt-get--no-cache postgresql-client

EXPOSE 5000

CMD ["sh", "-c", "npm start"]
