services:
  postgres_container:
    image: postgres:16-alpine
    container_name: postgres-container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 3s
      retries: 2

  student_api:
    build: .
    image: student_api:v1.0.0
    container_name: student_apps
    ports:
      - "${PORT}:${PORT}"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      postgres_container:
        condition: service_healthy

  migrate:
    build: .
    container_name: db_migrate_only
    command: npm run migrate #CMD
    depends_on:
      postgres_container:
        condition: service_healthy

volumes:
  postgres_data:
