.PHONY: docker-compose-up-student-app docker-compose-down-student-app

# Start the student-app service
docker-compose-up-student-app:
	docker compose up -d

# Stop the student-app service
docker-compose-down-student-app:
	docker compose down
