name: Self Hosted Runner
on:
 push:
  branches:
    - milestone_4
  paths:
    - milestone_4/**

permissions:
  contents: write

env:
  IMAGE_VERSION: 1.0.1
  MILESTONE_4_DIR: milestone_4

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      #--- Setting up Node
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: ${{ env.MILESTONE_4_DIR }}
        run: npm ci

      - name: Run tests
        working-directory: ${{ env.MILESTONE_4_DIR }}
        run: make test

      - name: Perform code linting
        working-directory: ${{ env.MILESTONE_4_DIR }}
        run: make lint

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: captianvigg06/student-api-repo:${{ env.IMAGE_VERSION }}
